<a href="https://colab.research.google.com/github/mmarinad/BD/blob/master/BigData_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

from nltk.tokenize import word_tokenize
from torch.autograd import Variable
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.optim as optim

In [0]:
corpus =[
    "I love Programming. I love Math. I tolerate Biology."
]

In [3]:
tokens=[]
for i in range(len(corpus)):
  sents = corpus[i].split(".")
  for j in range(len(sents)):
    tokens = tokens + sents[j].lower().split(" ")
tokens

['i',
 'love',
 'programming',
 '',
 'i',
 'love',
 'math',
 '',
 'i',
 'tolerate',
 'biology',
 '']

In [0]:
my_dict = list(set(tokens))  #unique words in corpus
vocab_size = len(my_dict)
w_list_size  = len(tokens)#size of tokens

In [5]:
print(my_dict) 

['', 'programming', 'love', 'tolerate', 'math', 'biology', 'i']


In [6]:
idx2word={}
word2idx={}

for ind,token in enumerate(my_dict):
  word2idx[token]=ind
  idx2word[ind]=token
print(idx2word)
print(word2idx)



{0: '', 1: 'programming', 2: 'love', 3: 'tolerate', 4: 'math', 5: 'biology', 6: 'i'}
{'': 0, 'programming': 1, 'love': 2, 'tolerate': 3, 'math': 4, 'biology': 5, 'i': 6}


In [7]:
ss=len(my_dict)
cooc = np.zeros((ss,ss))
cooc

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [8]:
for idx in range(len(tokens)-1):
  indx2= word2idx[tokens[idx+1]]
  indx1= word2idx[tokens[idx]]
  print(indx1)
  print(indx2)
  print(tokens[idx], tokens[idx+1])
  cooc[indx1, indx2] += 1
#print(cooc[5][6])
cooc

6
2
i love
2
1
love programming
1
0
programming 
0
6
 i
6
2
i love
2
4
love math
4
0
math 
0
6
 i
6
3
i tolerate
3
5
tolerate biology
5
0
biology 


array([[0., 0., 0., 0., 0., 0., 2.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 1., 0., 0., 0.]])

In [9]:
cooc_new = cooc*cooc.T
cooc_new

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])